server:
  port: 19911
  
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true       
  dubbo:
    application: 
      name: dubbo-sentine-consumer
      owner: wangbo
      environment: develop
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20811
csp:
  sentinel:
    application:
      dashboard: 127.0.0.1:8080
      port: 8723
    zookeeper:
      address: 127.0.0.1:2181