server:
  port: 19910
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  dubbo:
    application:
      name: dubbo-sentine-provider
      owner: wangbo
      environment: develop
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20811
csp:
  sentinel:
    application:
      dashboard: 127.0.0.1:8080
      name: dubbo-sentine-provider
      port: 8724
    zookeeper:
      address: 127.0.0.1:2181